version: '3'

services:
  app:
    image: fleedstix/devops-for-programmers-project-lvl1_app:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    volumes:
      - /pgdata:/var/lib/postgresql/data

volumes:
  pgdata: