---

version: '3'

services:
  app:
    image: fleedstix/devops-for-programmers-project-lvl1_app:latest
    command: bash -c 'sleep 3 && npm start'

  caddy:
    image: caddy:2.3.0
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    depends_on:
      - app

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: