version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./app:/app
    command: npm test
    depends_on:
      - db    

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data