version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: bash -c 'sleep 3 && npm start'
    depends_on:
      - db

  caddy:
    image: caddy:2.3.0
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    depends_on:
      - app

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data